### ISSUE TITLE
CI failure on master

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#101]
```
$ go test -v -race ./...
../../microcosm-cc/bluemonday/sanitize.go:38:2: cannot find package "golang.org/x/net/html" in any of:
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/golang.org/x/net/html (from $GOROOT)
	/home/travis/gopath/src/golang.org/x/net/html (from $GOPATH)
```

https://travis-ci.org/gopherjs/vecty/builds/216070003

**Comment by shurcooL** [comment]
Looks like a Travis issue, it's failing to fetch dependencies because it's being throttled:

```
$ go get -t -v ./...
github.com/gopherjs/gopherjs (download)
github.com/microcosm-cc/bluemonday (download)
Fetching https://golang.org/x/net/html?go-get=1
Parsing meta tags from https://golang.org/x/net/html?go-get=1 (status code 200)
get "golang.org/x/net/html": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/html?go-get=1
get "golang.org/x/net/html": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
# cd .; git clone https://go.googlesource.com/net /home/travis/gopath/src/golang.org/x/net
Cloning into '/home/travis/gopath/src/golang.org/x/net'...
remote: Daily bandwidth rate limit exceeded for IP 52.45.185.117
fatal: protocol error: bad pack header
package golang.org/x/net/html: exit status 128
github.com/russross/blackfriday (download)
github.com/shurcooL/sanitized_anchor_name (download)

The command "go get -t -v ./..." exited with 1.
```

See:

```
remote: Daily bandwidth rate limit exceeded for IP 52.45.185.117
```

**Comment by shurcooL** [comment]
This is quite strange. In my 3+ years of using Travis daily for dozens of repos, this is the first time I see it failing to fetch dependencies with this error message.

All my of Go repos have had their build pass successfully the last time it ran.

https://www.traviscistatus.com/ is not showing any known problems on their side.

Based on the error message `remote: Daily bandwidth rate limit exceeded for IP 52.45.185.117`, I'm guessing we don't have much of a choice but to wait a day and see if it gets resolved tomorrow.

**Comment by shurcooL** [comment]
Oh, I just realized that `golang.org/x/net` is hosted on Google git servers, not github. So it's possible it's a recent change to https://go.googlesource.com causing this.

Travis has some caching or option for caching on their side, but I've never had the need to investigate it too deeply. This might be a good cause for that.

**Comment by slimsag** [comment]
https://github.com/golang/go/issues/12933 looks highly related

I retriggered the build just now

**Comment by shurcooL** [comment]
What made you think it would work if you retried it?

I expect it to keep failing until tomorrow, since the error message says "**Daily** bandwidth rate limit exceeded".

I also saw that it failed when I created PR #102.

**Comment by slimsag** [comment]
Ah, you are right. I was skimming/reading too quickly.

**Comment by slimsag** [comment]
Looks like it has reset for the day / master has passed just now. I am guessing that https://github.com/gopherjs/vecty/pull/103 may help prevent this in the future. WDYT?

**Comment by xoviat** [comment]
Note that travis cache is like memcache. When it's there, it's fast, but it's not always there.

**Comment by shurcooL** [comment]
> Looks like it has reset for the day / master has passed just now.

Right, it's passing now.

![image](https://cloud.githubusercontent.com/assets/1924134/24437903/d65f02f0-1411-11e7-902b-da6c9779b5a4.png)

Should we close this issue then?
