### ISSUE TITLE
Restorer is not supported by Rerender

### ISSUE THREAD

**Issue by pdf** [gopherjs/vecty#106]
As `prev` is always passed as `nil` from `Rerender` to `doRestore`, there's no way for Components to function as a Restorer on Rerender.

https://github.com/gopherjs/vecty/blob/34ae77073fd923c6ab2f89c234a8ecf76f463cb0/dom.go#L298

Considering this is probably the primary use-case, it renders Restorer currently useless, except where used internally.

As it's currently broken for all(?) client code, if this can be fixed I'd also like to propose breaking the API to rename the method to something that parses lexically, like `ShouldUpdate` so that we can flip the boolean meaning.

It currently parses very painfully, since you implement a function called `Restore`, but what it actually means means is "don't update the DOM" if the return value is `true`.  Even if if it was readily apparent what `Restore` means from outside the rendering code, `Restore() -> true` meaning "don't restore" is a headache.

**Comment by pdf** [comment]
@slimsag I'm going to take a stab at fixing this, and in the process take a pass over the whole render chain, including tackling #25 and #92.  This may be invasive, but the current render chain seems overly brittle.

I realise that you're keen to get some tests in before accepting PRs, and I understand that you've had little time to work on this project recently, however I'd like to get something more robust working than what we currently have so that I can move on with my project.

My current plan is to build on #93 and #104, and sort out #94 using a different approach during the refactor.

If you have a moment to comment, and would prefer that I don't do any of this, or would suggest that this would be wasted, I'll put this aside and possibly take a look at some of the React bindings that seem to be maturing for this project.  I'd really like to see Vecty succeed though, would like to stay native if possible, and am happy to invest some time if warranted, but I need to commit to a path to move forward.

**Comment by pdf** [comment]
I went ahead and did it anyway, as I got into the flow last night: #107.

**Comment by slimsag** [comment]
For better context, I responded to that comment inline here instead: https://github.com/gopherjs/vecty/pull/107#issuecomment-300897887
