### ISSUE TITLE
"Removing" HTML properties by setting them to `nil`

### ISSUE THREAD

**Issue by pdf** [gopherjs/vecty#119]
For properties ([dom.go#L197](https://github.com/gopherjs/vecty/blob/51f78d76938df7d63c24d2ad6a56bc00f3d52e62/dom.go#L197)) and dataset keys ([dom.go#L226](https://github.com/gopherjs/vecty/blob/51f78d76938df7d63c24d2ad6a56bc00f3d52e62/dom.go#L226)) the current behaviour is to set removed keys to `nil`.  This doesn't seem right to me - is there a reason they're not actually `delete`d?

I have noticed some undesirable behaviour as a result of this code, like `<elem prop="nil">` being rendered by the browser.

**Comment by slimsag** [comment]
I completely agree with you. I think that those should both be a call to https://godoc.org/github.com/gopherjs/gopherjs/js#Object.Delete (we'll have to add to our `jsObject`)

**Comment by pdf** [comment]
Cool, I already have that change ready, but it's based on #118 for the tests.

**Comment by slimsag** [comment]
Just merged #118 -- so feel free to send 😃
