### ISSUE TITLE
incorrect rendering when elements are added or removed

### ISSUE THREAD

**Issue by crewjam** [gopherjs/vecty#121]
It seems that when re-rendering a component that has elements added or removed, something gets lost. Here is a minimal test case:

```
package main

import (
	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
	"github.com/gopherjs/vecty/event"
)

type C struct {
	vecty.Core

	Show bool
}

func (c *C) Render() *vecty.HTML {
	return elem.Body(
		elem.Heading1(vecty.Text("Test Case")),
		vecty.If(c.Show, elem.Heading2(vecty.Text("foo"))),
		elem.Button(vecty.Text("Toggle"),
			event.Click(func(e *vecty.Event) {
				c.Show = !c.Show
				vecty.Rerender(c)
			})),
	)
}

func main() {
	c := &C{}
	vecty.RenderBody(c)
}
```

I'd expect the `<h2>Foo</h2>` to appear and disappear when clicking the "Toggle" button. 

What actually happens is that the DOM ends up looking like this, after clicking toggle (notice the missing text inside the H2:

```
<body><h1>Test Case</h1><h2></h2><button>Toggle</button></body>
```

I would expect that it would be:

```
<body><h1>Test Case</h1><h2>foo</h2><button>Toggle</button></body>
```

**Comment by crewjam** [comment]
If you start with `c.Show = true` and click "toggle" the DOM looks like, which is even stranger:

```
<body><h1>Test Case</h1><button></button></body>
```

**Comment by crewjam** [comment]
So I think I've tracked this issue down to a bug in `reconcile()` when we hit the `"Incompatible node, start fresh"` path. Child elements of the incompatible nodes are merged, but then replaceNode() removes the new child elements.

A partial fix is to change [this line](https://github.com/gopherjs/vecty/blob/master/dom.go#L262) to read `if h.new || i >= len(prev.children) {`.

I can do a PR, but I'd like to get some validation that I'm on the right track first.

Thanks!

**Comment by pdf** [comment]
I remember seeing this issue when I did the last render rewrite, give me a moment and I'll take a look over it.

**Comment by pdf** [comment]
Apologies for this @crewjam - I had this change in some earlier code, but missed it during the merge that caused your issue.
