### ISSUE TITLE
(more) incorrect rendering with added/removed elements

### ISSUE THREAD

**Issue by crewjam** [gopherjs/vecty#123]
Thanks for the quick response in #121, folks! I'm afraid we don't quite have the issue licked. Here is a test case that also fails:

```
package main

import (
	"log"

	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
	"github.com/gopherjs/vecty/event"
)

type C struct {
	vecty.Core
	SubComponent *SubComponent
	Show         bool
}

func (c *C) Render() *vecty.HTML {
	if c.SubComponent == nil {
		c.SubComponent = &SubComponent{}
	}
	return elem.Body(
		elem.Heading1(vecty.Text("Test Case")),
		vecty.If(c.Show, c.SubComponent),
		elem.Button(vecty.Text("Toggle"),
			event.Click(func(e *vecty.Event) {
				c.Show = !c.Show
				vecty.Rerender(c)
			})),
	)
}

type SubComponent struct {
	vecty.Core
}

func (v *SubComponent) Render() *vecty.HTML {
	return elem.Div(
		elem.Heading2(vecty.Text("Subcomponent")),
		vecty.Text("Subcomponent Text"),
	)
}

func (v *SubComponent) Unmount() {
	log.Printf("never called -- should be?")
}

func main() {
	c := &C{Show: true}
	vecty.RenderBody(c)
}
```

In this case the text `"Subcomponent Text"` appears initially but when removing and re-adding the element it is not present. Also, it appears that the Unmount() function is not called. 

Documenting this for now, I'll do some more digging.

**Comment by pdf** [comment]
There are some known issues with mount/unmount events.  I have a strategy to makes them much more consistent that I hope to merge in the next few weeks, however I'm not sure exactly when I'll get to it.

I had handled component re-use (a component pointer that persists between renders, as you've got here) in another branch, however it diverged from the current code-base considerably.  I'll try to track down the change that applies to this issue and get a PR together for it.

**Comment by pdf** [comment]
@crewjam thanks for reporting, and apologies for the issues you've had getting up and running - you've caught the project during something of a transition phase.  Obviously we're trying not to break things as we work through it (and adding tests as we go, to make this process more reliable), but these refactors have been aimed at the more complex areas of the codebase.

Please let us know if you encounter any further issues.
