### ISSUE TITLE
examples directory should be renamed to example.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/vecty#128]
This is a really minor style nit, but I can't help but report it because this is one of the few remaining high quality repositories where I see a plural being used for a collection, which feels counter to idiomatic Go.

Reference: https://dmitri.shuralyov.com/idiomatic-go#use-singular-form-for-collection-repo-folder-name

This is already fixed in https://github.com/go-gl/example and https://github.com/neelance/graphql-go/tree/master/example.

**Comment by shurcooL** [comment]
@slimsag Do you with the rationale provided in this issue?

**Comment by slimsag** [comment]
Sorry for the (severely) delayed response! Yes, I agree, it should be renamed. :)

**Comment by shurcooL** [comment]
I think this applies to `docs` folder too, does it not?

See https://github.com/golang/go/tree/master/doc.

**Comment by slimsag** [comment]
Yep!
