### ISSUE TITLE
icon tag

### ISSUE THREAD

**Issue by XenLion** [gopherjs/vecty#133]
I just noticed that there is an HTML icon tag, <i>.  It appears Vecty is using this for italics.  Any way we could have support for both, officially?  Also, would you every include support for JSX?

**Comment by slimsag** [comment]
I don't know why you think `<i>` is an **icon** tag. It's italics:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i

Which issue in specific are you seeing?

> Also, would you every include support for JSX?

No, Vecty will not support JSX-like syntax. Sorry.

**Comment by pdf** [comment]
@slimsag icon libraries tend to hijack `<i>` to display icons, however @XenLion that should work fine with Vecty:

```go
elem.Italic(prop.Class("material-icons"), vecty.Text("accessibility"))
```

**Comment by XenLion** [comment]
I resolved it.  I was able to update the vecty source files to map a new Icon element to the <i> tag.  You're correct, it is italic.  However, it appears, that it is also used as an icon tag, as can be seen here:  https://semantic-ui.com/elements/icon.html.  I accidentally discovered it while using Bootstrap Studio.  But, it was pretty easy to add it in myself.  It works perfectly now.  I think it's used in font-awesome:  http://fontawesome.io/whats-new/.  Thanks for the help.

**Comment by pdf** [comment]
@XenLion there's no need to add another elem, it's the exact same markup.

**Comment by XenLion** [comment]
@pdf Now that I think about it, I guess you're right.  I probably could've used the italic element and still received the same or expected results.

**Comment by XenLion** [comment]
I agree.  I will remove it and just reuse the italics element.  Thanks for the clarification.
