### ISSUE TITLE
CustomEvent for when the actual DOM node is created

### ISSUE THREAD

**Issue by andrebq** [gopherjs/vecty#135]
Hi,

I'm creating this issue because I had a need to get the actual DOM node for one of my components. The use case was:

"When rendering a list of nodes, I want to scroll to the last element on that list".

This is can be done using "domNode.scrollIntoView()".

So, in order to enabled that I changed a few things on "vecty"

on "package event":
```
// DOMCreated is called when the given dom node is created but it might not
// be inserted into the DOM.
//
// Use RAF from withing this handler to ensure your node is present on the document.
func DOMCreated(listener func(ev *vecty.Event)) *vecty.EventListener {
	return &vecty.EventListener{
		Name:     "domcreated",
		Listener: listener,
	}
}

// RAF executes step on the next frame
func RAF(step func()) {
	js.Global.Call("requestAnimationFrame", step)
}
```
on "package vecty" (dom.go)
```
// Incompatible node, start fresh
if prev == nil {
	prev = &HTML{}
}
h.createNode()
defer func() {
	h.new = false

	// fire an event on the dom object
	doc := js.Global.Get("document")
	createEv := doc.Call("createEvent", "HTMLEvents")
	createEv.Call("initEvent", "domcreated", false, true)
	h.node.Call("dispatchEvent", createEv)
}()
```

Then in my component function:
```
func (m *MyComponent) scrollToView(ev *vecty.Event) {
	event.RAF(func() {
		ev.Target.Call("scrollIntoView")
	})
}

func (m *MyComponent) Render() *vecty.HTML {
	return elem.Article(
		event.DOMCreated(m.scrollToView),
		... // other nodes/attributes/etc...
	)
}
```

Using the RAF solution isn't pretty, but given how vecty works I think it'll work all the times and this is also a standard so we can trust that it will be present on the browsers.

I didn't included any polyfill or browser detection but this is just an idea.

There is no branch/fork since I want to know if this is a desired feature and if the implementation is OK.

Thanks in advance.

**Comment by pdf** [comment]
@andrebq there should be a `Mount` callback available for Components in the not-too-distant future that should give you what you want without resorting to `scrollIntoView`.

**Comment by slimsag** [comment]
I agree with what pdf said above.

**Comment by pdf** [comment]
@andrebq for reference, here's how you might use the new `Mounter` interface to scroll a component into view on mount:

```go
type MyComponent struct {
  vecty.Core
  target *vecty.HTML
}

func (c *MyComponent) Mount() {
  c.target.Node().Call("scrollIntoView")
}

func (c *MyComponent) Render() *vecty.HTML {
  // store a reference to our target element, for use in `Mount()`
  c.target = elem.Div()
  return c.target
}
```
