### ISSUE TITLE
Move storeutil into todomvc example subpackage

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#137]
`storeutil` is not a final API design, and I feel very uncertain about multiple aspects of it. I will move it into `example/todomvc/...` and users of it today can import from there or copy if they need it.

In the future, we'll come up with a better pattern.

**Comment by shurcooL** [comment]
The issue has help wanted label, but the text says "I will move it ...". That's confusing. Do you want a PR that moves it?

**Comment by slimsag** [comment]
@shurcooL sorry :) yes I wanted a PR that moves it, I wrote "I will move it" with the intent of communicating that this is a done-and-made decision not something I'd like to propose / discuss.

**Comment by shurcooL** [comment]
Gotcha. I guess you meant "_we_ will move it." :)
