### ISSUE TITLE
Think about how ComponentOrHTML and MarkupOrChild could be made into concrete types

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#156]
Today these two types are `interface{}` and easy to mix up. For example of this, see the Slack discussion [starting here](https://gophers.slack.com/archives/C0LBM1R0C/p1508292376000175).

It'd be good if we could make these types more concrete.

**Comment by myitcv** [comment]
@slimsag I mentioned on Slack I'd keep you updated on any progress in [`myitcv.io.react`](https://myitcv.io/react) on this subject.

Just put together a quick and dirty version of what things might look like, using `<ul>` and `<li>` elements as an example.

The `<ul>` element now [takes elements that implement the `react.RendersLi` interface](https://github.com/myitcv/react/blob/92faf2492ab7ffa0db65b2019459082f835351f9/ul_elem.go#L18):

```go
func Ul(props *UlProps, children ...RendersLi) *UlElem {
	// ...
}

type RendersLi interface {
	Element
	RendersLi(*LiElem)
}
```

Naturally, the `<li>` element itself [implements this interface](https://github.com/myitcv/react/blob/92faf2492ab7ffa0db65b2019459082f835351f9/li_elem.go#L11):

```go
func (l *LiElem) RendersLi(*LiElem) {}
```

But we can also have [user-defined components implement this interface](https://github.com/myitcv/react/blob/92faf2492ab7ffa0db65b2019459082f835351f9/examples/immtodoapp/entry.go#L21) and hence act as an `<li>` element:

```go
// ...

func Entry(s string) *EntryElem {
	return buildEntryElem(EntryProps{Text: s})
}

// ...

func (e EntryDef) Render() *react.LiElem {
	return react.Li(nil, react.S(e.Props().Text))
}

func (e EntryDef) RendersLi(*react.LiElem) {}
```

The type safety is enforced with the help of the [code generated "half" of each user-defined element](https://github.com/myitcv/react/blob/92faf2492ab7ffa0db65b2019459082f835351f9/examples/immtodoapp/gen_Entry_reactGen.go#L13-L18).

Which then means we can [use that user-defined component as an `<li>` element](https://github.com/myitcv/react/blob/92faf2492ab7ffa0db65b2019459082f835351f9/examples/immtodoapp/todo_app.go#L43-L51):

```go
var entries []react.RendersLi

for _, v := range t.State().items.Range() {
	entries = append(entries, Entry(v.name()))
}

// ...

react.Ul(nil, entries...)
```

Would be interested in any feedback.

**Comment by pdf** [comment]
@myitcv I wasn't planning on going this far with it, my plan was just to make `ComponentOrHTML` and `MarkupOrChild` more specific than the empty `interface{}` that they are now, so that users can at least get compile-time (rather than run-time) errors for invalid types.

Element container/child validity seems to me like a whole other rabbit-whole, and probably not something we'd tackle (if at all) until something may be done for #136, ie - this can be generated from some sensible source of truth.  Even then, I'm not sure the effort would be worth the pay-off, and the number of edge-cases may make it prohibitively costly to maintain, and I'm not entirely convinced that a proliferation of types to support all elements specifically is actually worthwhile.  Do you have some use-cases where this is beneficial @myitcv?

Thoughts @slimsag?

**Comment by myitcv** [comment]
@pdf 

> I wasn't planning on going this far with it

Apologies, I didn't include my comments for any reason other than to update on where I'd got to with `myitcv.io/react`. So no expectations as a result of me having commented!

> Element container/child validity seems to me like a whole other rabbit-whole

Very much agree. As one of [my TODO's](https://github.com/myitcv/react/wiki/TODO) I want to ultimately generate HTML elements, containment restrictions etc from the [HTML 5 spec](https://www.w3.org/TR/html5/). But I constantly vacillate on whether it's worth the effort or not, hence why I've  adopted a very permissive approach for now. 

A related question if I did go down this route would be how closely Chrome, Firefox etc follow the specs, or put another way, how permissive they are. I don't know how best to answer this question.

That said, the benefit of having an auto-generated library of HTML elements would be that there would be less incorrect HTML generated which would hopefully mean that browsers, with time, could be _less_ permissive. But maybe that's a pipe dream.

**Comment by slimsag** [comment]
@pdf 

> @myitcv I wasn't planning on going this far with it, my plan was just to make ComponentOrHTML and MarkupOrChild (if that sticks around once we do this) more specific than the empty interface{} that they are now, so that users can at least get compile-time (rather than run-time) errors for invalid types.
> ...
> Thoughts @slimsag?

I agree with this completely, I believe that doing what you've stated here would resolve this issue fully.

@myitcv's approach detailed above is quite interesting, but I think not feasible to implement at first glance (you basically must create a handwritten structure/methods for each HTML element and understand the intricacies of each them), and I am not sure it would create a better API.

@myitcv 

> As one of my TODO's I want to ultimately generate HTML elements, containment restrictions etc from the HTML 5 spec. But I constantly vacillate on whether it's worth the effort or not, hence why I've adopted a very permissive approach for now.

I'd be incredibly surprised if you can derive the element containment restrictions from the HTML spec, since it lacks so much concrete / consistent information in that regard. Also, if I was you I would be referencing the whatwg spec not the w3 HTML5 spec, but that is of course my personal preference, you should see replies like in a discussion like https://stackoverflow.com/questions/6825713/html5-w3c-vs-whatwg-which-gives-the-most-authoritative-spec and decide for yourself of course.

> That said, the benefit of having an auto-generated library of HTML elements would be that there would be less incorrect HTML generated which would hopefully mean that browsers, with time, could be less permissive. But maybe that's a pipe dream.

I do think that hoping browsers will one day be able to be less permissive is a pipe dream. After all, they must still render web pages created in the 90s. Anything we do in Go today will not heavily influence them at all. A larger ecosystem like Facebook's React itself may be able to (c.f. web components); but unlikely what we do ever will.

On the topic of ensuring correctness of HTML, my aim with Vecty would be that a linter could do it quite nicely / easily. But that would probably be so far down the road it's not even an active topic in my mind today.

**Comment by myitcv** [comment]
@slimsag 

> approach detailed above is quite interesting, but I think not feasible to implement at first glance (you basically must create a handwritten structure/methods for each HTML element and understand the intricacies of each them), and I am not sure it would create a better API.

Yes this is a definite difference in approach. My experience with Typescript has been that having typesafe attributes etc is worthwhile. Hence the path for `myitcv.io/react`, but I wouldn't go so far as to say it's better - just a preference. 

> I do think that hoping browsers will one day be able to be less permissive is a pipe dream.

100% agree with your comments; it was only something of an aside. But if either project produces more consistent HTML as a result, well that can only be a good thing. 

> On the topic of ensuring correctness of HTML, my aim with Vecty would be that a linter could do it quite nicely / easily.

Interesting, because this is something I've also toyed with. [`reactVet`](https://github.com/myitcv/react/tree/master/cmd/reactVet) is a _very_ early attempt at this, but honestly right now it doesn't do anything interesting other than helping do some lifting for my [primitive JSX support](https://godoc.org/myitcv.io/react/jsx). Would be interested to see what you do in this space too.

Thanks for the thoughts/feedback.

**Comment by pdf** [comment]
@slimsag do you have any specific ideas on implementation, ie - you mentioned the possibility of using an unexported method to firm up the types as one option.

**Comment by slimsag** [comment]
Yeah, so I will start writing my current thoughts here as multiple comments (in case you want to follow-along as I write) as a brain dump. First part:

# High Level: Problem constraints

At a high level, we currently need two things from these two [`ComponentOrHTML`](https://godoc.org/github.com/gopherjs/vecty#ComponentOrHTML) and [`MarkupOrChild`](https://godoc.org/github.com/gopherjs/vecty#MarkupOrChild) data types.

- `Tag` and `Text` must be able to accept (`Component`, `*HTML`, `List`, `KeyedList`, `nil`) OR `MarkupList`.
- `If` must be able to accept (`Component`, `*HTML`, `List`, `KeyedList`, `nil`) but NOT `MarkupList`.

Side note: `vecty.If` today misleading takes a parameter named `markup` of type `ComponentOrHTML` -- we should rename that to just `children` probably.

At its core, we're trying to represent a union type in Go, which obviously does not support them. Today we do it like this:

```Go
// ComponentOrHTML is one of `Component`, `*HTML`, `List`, `KeyedList`, `nil`
type ComponentOrHTML interface{}
```

**Comment by slimsag** [comment]
## Possible solution: a struct union type

Another way to do this would be with a struct type and fields:

```Go
// only one field is present (!= nil) at a time. It is illegal for two fields to be present.
//
// (*ComponentOrHTML)(nil) represents a nil.
type ComponentOrHTML struct {
    Component Component
    HTML *HTML
    List List
    KeyedList *KeyedList
}
```

Of course, the ugliness here is that, an API like the `Tag` function would become:

```Go
// (assume `MarkupOrChild` is like `ComponentOrHTML` above, but with a `MarkupList` field)
func Tag(tag string, m ...*MarkupOrChild) *HTML
```

The signature is fine -- but callers might not be. For example this code:

```Go
return Tag("body",
    Tag("hr"),
    someList,
)
```

suddenly becomes:

```Go
return Tag("body",
    &ComponentOrHTML{HTML: Tag("hr")},
    &ComponentOrHTML{List: someList},
)
```

Which is much uglier given how this makes up probably 99% of Vecty user code. Suddenly instead of dealing with type unsafety we must stuff `&ComponentOrHTML{...}` into every line.

What we could do to solve this ugliness aspect is to ensure most things already return `*ComponentOrHTML`. For example if `Tag` returned it, and maybe if `List` was a function returning it (and `List.WithKey` would either became a function `ListWithKey` OR become a method on `ComponentOrHTML`?) then we would have:

```Go
return Tag("body",
    Tag("hr"),
    someList,
)
```

Of course this means iterating over `someList` now becomes `someList.List` or slightly more complex, and still, `*ComponentOrHTML` is stuffed everywhere in our API. :/ The real trouble here is just figuring out what such an API would look like, since it would in fact probably change a very large portion of our API.

**Comment by pdf** [comment]
This seems like the worst-case option.

**Comment by slimsag** [comment]
# Possible solution 2: unexported method

The second idea I had was an unexported method. This would mean we define `ComponentOrHTML` as:

```diff
-type ComponentOrHTML interface{}
+type ComponentOrHTML interface{
+    isComponentOrHTML()
+}
```

_Normally_, people complain about this being a bad idea because exposing private things in a public API feels hacky, and interfaces 'are meant to be extended' by others. We could expose `isComponentOrHTML` (by capitalizing the `i`) but that would be silly because none of our code could handle it anyway and it would just litter our API documentation needlessly.

Once we did this we would alter each other type that we need to represent (`Component`, `*HTML`, `List` and `KeyedList`) to expose an `isComponentOrHTML` method. This means all of these are checked by the compiler as implementing that interface at compile time, which I think solves what we want here.

We would have a similar type for `MarkupOrChild`:

```diff
-type MarkupOrChild interface{}
+type MarkupOrChild interface{
+    isComponentOrHTML()
+    isMarkupList()
+}
```

and would add a `isMarkupList` method to `MarkupList`.

Are there drawbacks to this approach I haven't thought of, though? I am not sure. Thus far, it's the best idea I have come up with.

I don't have any other ideas here.

**Comment by slimsag** [comment]
> This seems like the worst-case option.

Agreed. I think the struct union type is not a good one.

**Comment by pdf** [comment]
> Normally, people complain about this being a bad idea

As you rightly point out, vecty must be the source of valid types here, for us to be able to do anything useful with them, so I think we can get away with it, even though it doesn't feel ideal.

> We would have a similar type for MarkupOrChild:

This can't work, unless _everything_ has a `isMarkupList()` method (the union types problem).

**Comment by slimsag** [comment]
> This can't work, unless everything has a isMarkupList() method (the union types problem).

Yes, true. I didn't think that part through enough.

But I think adding `isMarkupList` to everything would be completely fine.

**Comment by pdf** [comment]
> But I think adding isMarkupList to everything would be completely fine.

In that case I think it just has to be called `isMarkupOrChild`, then the interfaces are simply:

```go
type MarkupOrChild interface {
    isMarkupOrChild()
}

type ComponentOrHTML struct {
    isComponentOrHTML()
}
```

**Comment by slimsag** [comment]
Yep! that's exactly what I was thinking (also there is a typo in that last one, s/struct/interface/g)

**Comment by pdf** [comment]
This is pretty straight-forward then, I think, shouldn't even result in an API breakage for users.

**Comment by slimsag** [comment]
yeah now that I've written it out I feel more confident about it. Unless there is something unforeseen that I didn't think of.

**Comment by pdf** [comment]
I'll get this queued up to follow #158, hopefully have time to sort it out either today or tomorrow.

**Comment by iafan** [comment]
Just a thought: can there be a single interface that will satisfy both needs? I.e. a single Component interface that says that it should have Render(), Context() and Apply() methods, where implementations will have some of these methods empty if they don't need them?

**Comment by pdf** [comment]
@iafan it's certainly possible, however that clutters the public API for every type, whereas the proposed solution does not.
