### ISSUE TITLE
vecty.MarkupIf can be illegally passed to elem.Body (and it works)

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#157]
@iafan boiled down his issue that he reported over Slack down to:

```Go
    return elem.Body(
        vecty.MarkupIf(a.isDrawingMode, vecty.Class("drawingmode")),
        //...
    )
```

> When the style is toggled on `<body>` tag, the whole app gets re-rendered. If I comment-out the `vecty.MarkupIf(...)` line, the tree becomes stable (only the drawing layer div will be mounted/unmounted). (edited)

The problem here is that `vecty.MarkupIf` passed directly into `elem.Body` (without `vecty.Markup(...)`) works completely fine:

1. It doesn't panic (it should)
2. It actually applies the markup! (it should not).

**Comment by pdf** [comment]
Fixing #156 would fix this as a by-product.

**Comment by slimsag** [comment]
@iafan Thanks to @pdf fixing https://github.com/gopherjs/vecty/issues/156 this is no longer an issue. The compiler now ensures passing `vecty.MarkupIf` into any tag constructor is impossible. :)
