### ISSUE TITLE
Potential bug? Doesn't `vecty.MarkupIf` consume a child slot?

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#173]
I noticed that `MarkupIf` returns `nil` when the `cond` is `false` -- my assumption was that it should probably return an empty `MarkupList` otherwise it looks the same as regular `vecty.If` and consumes a child slot. This is probably just a copy-paste error?

https://github.com/gopherjs/vecty/blob/1ba2b77c9d1fbf3503d3ddaa1cfc25dff4516ea3/markup.go#L220-L226

@pdf WDYT? Am I right here or am I missing something?

**Comment by pdf** [comment]
Only valid inside `Markup()`

**Comment by slimsag** [comment]
Ahhh, yep, that's it. I missed that. Thanks!
