### ISSUE TITLE
example/todomvc using outdated Restorer API

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#174]
https://github.com/gopherjs/vecty/blob/1ba2b77c9d1fbf3503d3ddaa1cfc25dff4516ea3/example/todomvc/components/itemview.go#L26-L32

We should remove this (also one in `pageview.go`).

**Comment by tbruyelle** [comment]
For my interest, the fix is to remove this method and tagging the related fields with `vecty:"props"` ?

**Comment by slimsag** [comment]
@tbruyelle No, the fix is to just remove this method entirely. In e.g. the above snippet, it copied the old `editing` and `editTitle` state values over to the new component instance. But now, as long as a struct field is _not tagged_ `vecty:"props"` this happens automatically. That is, all fields are copied over except those tagged `vecty:"props"` because they are properties passed down from the parent component.

**Comment by tbruyelle** [comment]
@slimsag Thanks so I understood the inverse on `vecty:"props"` !
