### ISSUE TITLE
Unsafe HTML injection

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#20]
Something akin to React's [dangerouslySetInnerHTML](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) is needed.

**Comment by shurcooL** [comment]
Sounds reasonable. I'd be okay if this doesn't land right away in case it's not very straightforward to support.

In fact, it'd be nice to dogfood the safe HTML generation more by being unable to use unsafe HTML.

**Comment by slimsag** [comment]
We need to have a good story for it in terms of e.g. how you would render Markdown. You don't want to write an entire Markdown -> Vecty translator :) (well, you might, but not right away).

**Comment by shurcooL** [comment]
Fair enough. But on the topic of a Markdown renderer, in theory, it should be possible to implement the `blackfriday.Renderer` interface to do just that.

**Comment by bep** [comment]
Not sure this is applicable to this particular issue, but thought I throw it into the mix:

```
React 15 brings significant improvements to how we interact with the DOM:

    We are now using document.createElement instead of setting innerHTML when mounting components. This allows us to get rid of the data-reactid attribute on every node and make the DOM lighter. Using document.createElement is also faster in modern browsers and fixes a number of edge cases related to SVG elements and running multiple copies of React on the same page.
```

**Comment by slimsag** [comment]
FYI @bep the article you quoted is talking about for the initial mounting of components; in which case Vecty already uses `document.createElement` directly anyway. `innerHTML` would only be used in the scenario of injecting raw HTML, like React's `dangerouslySetInnerHTML`
