### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by gedw99** [gopherjs/vecty#208]
Sorry to bring this up as I think it's been churned over a fair bit but are there any vecty MDC projects happening.

I saw two that have stalled it seems.
Amigo has one but it's no getting any action.

I have to build an admin GUI and so it's does not need front end Devs involved so I can use vecty without getting in trouble with the front-end Devs :)

**Comment by slimsag** [comment]
While not specifically about material design, https://github.com/gopherjs/vecty/issues/188 is where this would come in some official capacity so I will close this issue in favor of that one for tracking purposes.
