### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#211]
This is probably very easy/straightforward to add. We can keep GopherJS support using build tags.

**Comment by gedw99** [comment]
Pretty smarty approach too.

Can even use both together for best performance.
Wasm in the web workers.
Gopherjs in the main Window.

**Comment by divan** [comment]
What about this project - 
https://github.com/gowasm/vecty?

**Comment by gedw99** [comment]
he says in his readme that its "hopefully temporary", so he probably wants to upstream it to Vecty.
Maybe worth asking him @slimsag

**Comment by gedw99** [comment]
@slimsag @damz 
i just saw that there is a PR for this !
https://github.com/gopherjs/vecty/pull/215
