### ISSUE TITLE
Keep textareas in sync

### ISSUE THREAD

**Issue by millerlogic** [gopherjs/vecty#221]
Hi, I'm not able to keep two textarea text in sync. It works fine if I only type into one textarea, but as soon as I type into the opposite one, nothing works anymore. Can anyone offer assistance? thanks

```go
package main

import (
	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
	"github.com/gopherjs/vecty/event"
)

func main() {
	vecty.SetTitle("Hello Demo")
	vecty.RenderBody(&PageView{
		Input: `hello world`,
	})
}

// PageView is our main page component.
type PageView struct {
	vecty.Core
	Input string
}

// Render implements the vecty.Component interface.
func (p *PageView) Render() vecty.ComponentOrHTML {
	return elem.Body(
		elem.Div(
			elem.Heading1(vecty.Text("Foo:")),
			elem.TextArea(
				vecty.Markup(
					vecty.Style("font-family", "monospace"),
					vecty.Property("rows", 5),
					vecty.Property("cols", 70),
					event.Input(func(e *vecty.Event) {
						p.Input = e.Target.Get("value").String()
						vecty.Rerender(p)
					}),
				),
				vecty.Text(p.Input), // initial textarea text.
			),
		),

		elem.Div(
			elem.Heading1(vecty.Text("Bar:")),
			elem.TextArea(
				vecty.Markup(
					vecty.Style("font-family", "monospace"),
					vecty.Property("rows", 5),
					vecty.Property("cols", 70),
					event.Input(func(e *vecty.Event) {
						p.Input = e.Target.Get("value").String()
						vecty.Rerender(p)
					}),
				),
				vecty.Text(p.Input), // initial textarea text.
			),
		),
	)
}
```

**Comment by millerlogic** [comment]
Same thing on chromium and firefox, so I assume it's not just a browser fluke.

Actually if you inspect element, you can even see the text updating in real time, but the page does not reflect the update.

**Comment by millerlogic** [comment]
Fixed it by switching to ```vecty.Property("value", p.Input)```
not really sure why it works this way, but it's solved.

**Comment by slimsag** [comment]
Apologies I won't have time to debug this for a while, but without a doubt this is due to rerendering. Usually this happens (not just in Vecty, but also e.g. in React) because on a rerender you are recreating the textarea element (which clears the value to default) OR because you are overriding the value with one that you don't want (your "initial text area value")
