### ISSUE TITLE
prop: naming inconsistencies

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#24]
Creating this as an issue and not a PR because I'm not sure we should do anything about it..

We might consider renaming these to match the `elem` and `style` naming schemes (of not using short-hand versions or acronyms):

1. `prop.Href` -> `prop.HypertextReference`
2. `prop.Id` -> `prop.Identity`
3. `prop.Src` -> `prop.Source`

The first two are by far much less digestible to me as an end-user.

**Comment by shurcooL** [comment]
How does the recent `Element` -> `Elem` and `Property` -> `Prop` change tie in here?

I might be missing contedxt, but `Href`, `Id` are much more readable to me (being familiar with HTML lingo) than `HypertextReference` and `Identity`... Unless they're supposed to represent something else?

**Comment by slimsag** [comment]
For example, we rename the `<h1>` tag to become `elem.Header1` here: https://github.com/gopherjs/vecty/blob/master/elem/generate.go#L34

I agree that `Href` and `Id` are more readable.. and that makes me uncertain of the naming scheme/remapping used by the `elem` `event` and `style` packages.

**Comment by neelance** [comment]
Rob Pike: `Length is not a virtue in a name; clarity of expression is.`

For example `Header1` instead of `H1` conveys a lot more information. But what the heck does a `HypertextReference` do? ;-) I think `href` is so common, everyone knows it.
However, it might be good to stay consistent, at least inside of each package. I opted for longer element names because the acronyms of HTML tags are really bad and some of them already have longer class names in the DOM API. Properties and styles however already have proper names in the DOM API, so I think we should keep them.

**Comment by bep** [comment]
Go's vet tool will complain about `Id` and suggest `ID`, at least in vars like `elementID`.

**Comment by slimsag** [comment]
@neelance thanks for clearing this up :) I think what you said makes sense, and from creating this issue that is exactly what I wanted to find out: what exactly is the name remapping pattern? I think you answered that clearly and I'm happy with it :+1:

@neelance @bep maybe we should `Id -> ID` and `Href` -> `HRef` ?

**Comment by bep** [comment]
I watch this repo with interest as this is something I need and want, so I have no strong meaning about this. But getting the names right before people start using it it saves a lot of trouble. I did a major naming cleanup of the API of Hugo a couple of months ago ... A lot of work with all the themes etc ...

**Comment by shurcooL** [comment]
> `Id -> ID`

Definitely. Consider [`honnef.co/go/js/dom`](https://godoc.org/honnef.co/go/js/dom) a good example. It has `GetElementByID` not `getElementById`.

About `Href`, I'm unsure that `HRef` is better. I consider "href" to be one weird word. Also see https://godoc.org/honnef.co/go/js/dom#HTMLLinkElement.Href.

**Comment by slimsag** [comment]
> About Href, I'm unsure that HRef is better. I consider "href" to be one weird word. Also see https://godoc.org/honnef.co/go/js/dom#HTMLLinkElement.Href.

FWIW I agree with your stance and think that `Href` reads better than `HRef`. But, we're being inconsistent, because `href` does stand for `Hypertext Reference` (two words), so... maybe we can blame HTML naming horror :scream:

**Comment by neelance** [comment]
I also consider `Href` as a weird word, same as @shurcooL.

**Comment by dominikh** [comment]
Generally speaking, I'm :+1: for `ID` and `Href`. Yes, `Href` technically stands for two words. However, `ID` technically stands for one word, yet is treated like an acronym. We have some freedom in mangling names ;)

**Comment by slimsag** [comment]
Sounds like we all agree to go with `ID` and `Href`, I've created https://github.com/gopherjs/vecty/pull/32 to switch to `ID`. PTAL.
