### ISSUE TITLE
How do you do web3.js addition into this code? and...

### ISSUE THREAD

**Issue by hiqsociety** [gopherjs/vecty#240]
1. How do you do web3.js addition into this code? and...
2. Any examples for calling rest api (from golang backend) etc?

**Comment by slimsag** [comment]
> Any examples for calling rest api (from golang backend) etc?

None yet, you can use the standard net/http library for this. See also #31

**Comment by slimsag** [comment]
> How do you do web3.js addition into this code? and...

It doesn't look like web3.js does any frontend rendering at all, so it's not really related to Vecty. I see you've already asked this here: https://github.com/gopherjs/gopherjs/issues/927 so I will close this in favor of that.
