### ISSUE TITLE
fail to produce 2.3KB wasm binary from example

### ISSUE THREAD

**Issue by leafbebop** [gopherjs/vecty#241]
Hi, I am building example/hellovecty. While everything works, the binary go compiler produce is 2.3M instead of 2.3KB in the readme.

Is it a typo in readme or there is some steps I need to follow to reduce the binary size? Thank you.

go version:

> go version go1.12.4 linux/amd64

**Comment by Andoryuuta** [comment]
Yeah, it looks like this was a typo. @slimsag fixed and explained it in [this PR](https://github.com/gopherjs/vecty/pull/242).

The correct bundle size of `hellovecty` w/ WASM is 2.3MB (0.5MB compressed).

**Comment by slimsag** [comment]
@Andoryuuta is correct, see https://github.com/gopherjs/vecty/pull/242 for an explanation. Apologies for the confusion!
