### ISSUE TITLE
Vecty does not compile with Go 1.14

### ISSUE THREAD

**Issue by marwan-at-work** [gopherjs/vecty#253]
I believe Go 1.14 introduces breaking changes in terms of comparing js.Value with the `==` operator. We now must use the `Equal` method instead of the operator. 

I tried changing all the operators which made Vecty compile but introduced new runtime errors. I'll try to dig into it a little more when I get some free time, but I just wanted to open the issue in case someone has already figured it out :) 

Thanks

**Comment by JalonSolov** [comment]
From the Go 1.14 release notes:

**WebAssembly**

JavaScript values referenced from Go via js.Value objects can now be garbage collected.

js.Value values can no longer be compared using the == operator, and instead must be compared using their Equal method.

js.Value now has IsUndefined, IsNull, and IsNaN methods.
