### ISSUE TITLE
document how to skip/short-circuit reconciliation

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#27]
If e.g. you are certain that the body / what `Render` returns will not have changed.

**Comment by influx6** [comment]
One of the major reasons I followed a non-node approach in my old Haiku experiment was in trying to solve this issue, from what I learnt, you guys need to have a form of identification of a current state of your dom possible in a Hash attribute for every node, which will allow you to identify which node has exactly changed, that is every time a node changes, this hash attribute is update and you can use it to track which elements within a DOM tree has infact changed.
