### ISSUE TITLE
templating

### ISSUE THREAD

**Issue by joeblew99** [gopherjs/vecty#42]
i played around with vecty on the weekend.
Really great feel to it.

I am now thinking about Templating. The Render command for React is great because its so simple.
Does anyone have any thoughts so this ?
Is there gopherjs support for doing templating in the browser ?

**Comment by influx6** [comment]
Personally, I think the key and usefulness of Vecty DOM API is that it abstracts out the need for such systems which could tend to be a hard mess to managed (Trust me I have played with a fully template based approach, works but gets spaghetti real quick). 

By using a more pure Go object approach, you get the power of the underline system and the expressiveness of the language itself. 
Yes templates do make it easy to express somethings but that is in truth, subjective not objective.

Once you build your mind around objects which transforms into markup themselves, it provides you a leverage, For example:

If or rather when vecty fully separates the rendering DOM from the core of its DOM API, you can practically build custom renderers which will take that same structure and produce appropriate outputs for whatever end results that is needed.

That flexibility is the core idea I believe that makes this approach better.

**Comment by joeblew99** [comment]
Are you referring to templating using the react "render" function , or to the golang template function ?

**Comment by joeblew99** [comment]
The strength of the react render function is that it does the virtual Dom differencing.
My intention is to implement that.

**Comment by influx6** [comment]
Ah! I see, I was referring to the go template function. Well I had taken @neelance work with is DOM and refined it to diff, so hope it helps with inspiration, you can find it here 

https://github.com/influx6/gu/blob/master/guviews/views.go#L288-L290

https://github.com/influx6/gu/blob/master/gutrees/elems.go#L264-L374

**Comment by neelance** [comment]
@joeblew99 Are you aware that vecty does "virtual dom differencing"?

**Comment by joeblew99** [comment]
I didn't. Thanks for pointing this out. 
I just found slimsags new component rendering code too.
This is really making great strides.

There is a project on github that unified the react native & react web API. I was thinking about the best way to reuse the gopherjs code between both client types.
I will dig it out if your interested.. It might be relevant to the slimdag component PR that everyone is discussing currently.

Again thanks for informing me.
Am closing this as it's clearly being discussed already
