### ISSUE TITLE
Element-level Mount and Unmount events

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#58]
We should support giving elements (not components) a callback when the element is mounted into the DOM / unmounted from the DOM.

**Comment by davelondon** [comment]
Yes - I found this is definitely needed for non-trivial examples. This is the only reason I'm currently working with a fork. 

[Here's how I added the Unmount event](https://github.com/davelondon/vecty/commit/6079f319fc136c3b8b568744dab980157715c00e). Initially I also added a Mount event too, but found it wasn't really necessary. Let me know what you think.

**Comment by davelondon** [comment]
p.s. I initially added Mount too, but found this wasn't really needed. When you call the view's constructor you're always adding it to the DOM, so it doesn't really need a special event.
