### ISSUE TITLE
Element that renders no markup?

### ISSUE THREAD

**Issue by davelondon** [gopherjs/vecty#59]
Several times it's I've wanted to return nothing from my view render function. This doesn't seem to be supported currently. Usually I've kludged it by returning an empty DIV, but that's not ideal. 

[Here's a stab](https://github.com/davelondon/vecty/commit/5fa136289be675934037691817742335ee53a275) at a `vecty.Nil()`. I'll continue dog-fooding it and see if there's any problems.

**Comment by bep** [comment]
I would name it `vecty.Discard` -- which is inline with similar in Go's stdlib.

**Comment by slimsag** [comment]
As discussed on #vecty Slack, one thing we'll have to deal with for this is the lack of a element to create contents in once the component does want to render something. Not impossible to do, I think, so I still consider this a good idea.
