### ISSUE TITLE
Need to expose the native event object

### ISSUE THREAD

**Issue by davelondon** [gopherjs/vecty#65]
In order to do a drag+drop file upload, you need access to `dataTransfer` from the js event. The js native event object isn't currently presented to the vecty event handler. I've added this in my fork as an anonymous struct member, and it seems to feel good in use:

https://github.com/davelondon/uploader/blob/master/editor.go#L133

I seem to remember this was discussed before?

**Comment by shurcooL** [comment]
> need access to `dataTransfer` from the js event. The js native event object isn't currently presented to the vecty event handler.

Just asking, but have you considered simply filling that gap and exposing `dataTransfer` natively?

**Comment by slimsag** [comment]
I think this is a duplicate or related to https://github.com/gopherjs/vecty/issues/55

I agree it is limiting, and the best choice for now is probably to expose the native event object. Although in #55 neelance does make some good points about event pooling in the future.. I'm not sure yet.

**Comment by slimsag** [comment]
Let's keep this all in #55 -- I've moved our comments over to there. Closing.
