### ISSUE TITLE
Expose a way to do work on requestAnimationFrame

### ISSUE THREAD

**Issue by shazow** [gopherjs/vecty#79]
Seems like a fairly natural thing that a lot of apps do (especially games), and a better practice than using `time.Tick`.

**Comment by shazow** [comment]
Handy reference from @influx6 on the slack: https://github.com/influx6/faux/blob/master/raf/raf.go

**Comment by slimsag** [comment]
Once #152 is merged, `vecty.Rerender` on a component uses `requestAnimationFrame` internally. That is: to animate a component, use `vecty.Rerender`.

Other potential uses of `requestAnimationFrame` are not covered (i.e. we don't literally expose that function), but I think that is fine / not in the scope for Vecty.
