### ISSUE TITLE
Unable to specify vendor prefixes

### ISSUE THREAD

**Issue by slimsag** [gopherjs/vecty#86]
Reported by @thearchitect in https://github.com/gopherjs/vecty/pull/82

> For example
> ```go
> elem.Div(
> 	vecty.Style("display", "-ms-flexbox"),
> 	vecty.Style("display", "-webkit-box"),
> 	vecty.Style("display", "-moz-box"),
> 	vecty.Style("display", "-ms-box"),
> 	vecty.Style("display", "box"),
> )
> ```
> will try to set only `display: box`.

**Comment by slimsag** [comment]
See comments starting at https://github.com/gopherjs/vecty/pull/82#issuecomment-279260222

**Comment by pdf** [comment]
Do we need to approach this similarly to #80?

**Comment by slimsag** [comment]
@pdf Maybe. I am not sure.

The big open question here is, if you want to specify some vendor prefixed CSS styles as shown in the issue description, how does that actually happen with [`HTMLElement.style`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style)?

Does that DOM object even support specifying vendor prefix CSS styles? I'm not sure. Basically, we need to figure out what this looks like in plain JS before we figure out how to support it in the Vecty API.

**Comment by pdf** [comment]
Ack.

**Comment by pdf** [comment]
I took a quick look at this, and my understanding is that there's no way to support this using the DOM API.  The only way I can see of doing the 'right' thing here would be to implement browser detection and a prefix database for overrides, but I really don't think this is a path we want to go down.  The autoprefixer DB is over half a MB, for example.

**Comment by slimsag** [comment]
You seem to be referencing some common autoprefixer DB? Could you point me to it? I am not familiar.

I haven't looked yet, but I wonder how things like http://leaverou.github.io/prefixfree/ work.

What I believe to be true is that:

```
elem.Div(
	vecty.Style("display", "-ms-foobar"),
	vecty.Style("display", "-webkit-foobar"),
)
```

Can never work in terms of the DOM API because [`HTMLElement.style`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) really is just a map where a single key (`display`) has a single value (whichever is specified last).

Of course, where the key is different, it will work fine:

```
elem.Div(
	vecty.Style("-ms-foobar", "xyz"),
	vecty.Style("-webkit-foobar", "xyz"),
)
```

So this is probably not possible, as you said, and is just another good example of how CSS is not really usable from within JavaScript fully. For example, we also can't set psuedo class rules without manipulating a stylesheet object: https://stackoverflow.com/questions/311052/setting-css-pseudo-class-rules-from-javascript

Maybe this all folds into #22

**Comment by pdf** [comment]
> You seem to be referencing some common autoprefixer DB?

Just the autoprefixer npm module, which is a CSS pre-processor that prefixes stylesheets, and is used in a lot of JS build workflows.  It works there, because it's used to build static assets, but obviously we don't want that sort of hefty codebase in the frontend, not to mention that the maintenance overhead would be a massive distraction.

I don't think we can do anything to fix this particular issue, so probably close it in favour of #22 happening one day.

PS - I am currently dealing with >50% packet loss to Github, thanks to some BGP hickup that is sending all my traffic via Europe to get there, hopefully my comments make it through, but it's a bit hit and miss so I may give up for now.

**Comment by slimsag** [comment]
Closing in favor of #22
