### ISSUE TITLE
Heading elements (h1, h2, h3, h4, h5, h6) are named Header.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/vecty#88]
I believe the correct name for https://godoc.org/github.com/gopherjs/vecty/elem#Header1 should be `Heading1`, not `Header1`. Same for 2, 3, 4, 5, 6.

The documentation correctly refers to them as heading elements.

> Head**ing** elements implement six levels of document headings, \<h1\> is the most important and \<h6\> is the least. A heading element briefly describes the topic of the section it introduces. Heading information may be used by user agents, for example, to construct a table of contents for a document automatically.
>
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

I've seen a similar issue happen in https://github.com/russross/blackfriday/issues/330.

An alternative naming that would also be valid is `H1`, etc.

**Comment by slimsag** [comment]
Good catch! We do use the longer forms, so `Heading1` SGTM

**Comment by shurcooL** [comment]
Made PR #89 that resolves this.
