### ISSUE TITLE
Document that using vecty.Style is preferable over vecty.Property("style", ...).

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/vecty#90]
I've asked what's the difference between the two in https://gophers.slack.com/archives/vecty/p1488148154608710, and @slimsag gave a great answer/explanation.

It should be a part of vecty documentation, whether the godoc, or somewhere else that goes over these things.

https://godoc.org/github.com/gopherjs/vecty#Property does not say anything about "style" being a special case right now.

It does say:

> Generally, this function is not used directly but rather the style subpackage (which is type safe) is used instead.

But that seems a little unclear and not completely relevant.

**Comment by slimsag** [comment]
> Generally, this function is not used directly but rather the style subpackage (which is type safe) is used instead.

This should actually read `but rather the style and prop subpackages (which are typesafe) should be used instead.`

It might make sense to actually disallow / strictly enforce use of `vecty.Style` by panicking in `vecty.Property("style", ...)` -- but I'll have to think about that some more.

**Comment by shurcooL** [comment]
> It might make sense to actually disallow / strictly enforce use of `vecty.Style` by panicking in `vecty.Property("style", ...)` -- but I'll have to think about that some more.

@slimsag, I have found a _very_ convincing reason to do that.

Consider the following program:

```Go
package main

import (
	"github.com/gopherjs/vecty"
	"github.com/gopherjs/vecty/elem"
	"golang.org/x/net/html/atom"
)

func main() {
	vecty.RenderBody(&Body{})
}

type Body struct {
	vecty.Core
}

func (*Body) Render() *vecty.HTML {
	return elem.Body(
		vecty.Property(atom.Style.String(), "background-color: hsl(209, 51%, 92%);"),
		elem.Span(
			vecty.Text("Body"),
		),
	)
}
```

It works fine in Chrome, Firefox. It does not work in latest Safari (10.1).

In addition to not working, the error message is extremely confusing and misleading, due to https://github.com/gopherjs/gopherjs/issues/616. This is what you see in Safari console:

![image](https://cloud.githubusercontent.com/assets/1924134/24380429/469c7826-1319-11e7-8c21-bc739bbfd5e5.png)

The stack trace and "TypeError: Attempted to assign to readonly property." text lead me to believe it was a problem with GopherJS, something about goroutines and scheduling. In reality, it seems Safari is the only browser that enforces not being able to assign to the readonly property called "style". (/cc @neelance, FYI.)

When I debugged GopherJS compiler by adding a `console.error(err);`, I saw where the error was actually coming from:

![image](https://cloud.githubusercontent.com/assets/1924134/24380508/ae0101c6-1319-11e7-9e05-a840026b1ab6.png)

And I was able to figure out that it was setting `style` property that was causing it. But I certainly don't wish for other vecty users to fall in this same trap.

In practice, doing `vecty.Property("style", ...)` doesn't seem to work in Safari, so it can't be reliably used, so it's in vecty's best interest to both document it and make help users catch their mistake.

---

For reference, rewriting the `Render` method to this fixes the rendering issue in Safari:

```Go
func (*Body) Render() *vecty.HTML {
	return elem.Body(
		//vecty.Property(atom.Style.String(), "background-color: hsl(209, 51%, 92%);"),
		vecty.Style("background-color", "hsl(209, 51%, 92%)"),
		elem.Span(
			vecty.Text("Body"),
		),
	)
}
```

**Comment by shurcooL** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style:

> ### Setting style
>
> Styles can be set by assigning a string directly to the style property (as in `elt.style = "color: blue;"`), which forwards it as `elt.style.cssText = "color:blue;"`, though it returns a `CSSStyleDeclaration` object which is read-only.

So it is possible to set `style` property, but it should be done by setting `style.cssText` instead.

I can confirm the following patch to `HTML.Restore` makes `vecty.Property("style", ...)` work in Safari:

```diff
diff --git a/dom.go b/dom.go
index 7ee1c9c..e8bb454 100644
--- a/dom.go
+++ b/dom.go
@@ -233,6 +233,10 @@ func (h *HTML) Restore(old ComponentOrHTML) {
 		h.Node.Set("innerHTML", h.innerHTML)
 	}
 	for name, value := range h.properties {
+		if name == "style" {
+			h.Node.Get("style").Set("cssText", value)
+			continue
+		}
 		h.Node.Set(name, value)
 	}
 	for name, value := range h.attributes {
```

But, not sure if you want to do that, since you said using `style` package or `vecty.Style` is meant to be the preferred way of setting styles.

**Comment by slimsag** [comment]
Thanks for the info @shurcooL ! That is super useful.

I don't think that we should do the `cssText` modification you spoke of in your second post, and the reason being is actually something I mentioned earlier in that Slack conversation in the description:

> Consider if you e.g. change a property like text-align to left, in the first one Vecty only has to update a single property (node.style["text-align"] = "left") whereas in the second one the browser has to update all of those properties (hopefully it is smart enough not to, but I'm not sure)

The right solution here, I think, is documenting+implementing the `vecty.Property` function as panicking if `style` is the property name passed in, and pointing users towards `vecty.Style` instead. If anyone wants, please feel free to send a PR for that (or else I will probably over the weekend)

**Comment by shurcooL** [comment]
> the reason being is actually something I mentioned earlier in that Slack conversation in the description ...  pointing users towards `vecty.Style` instead

Just want to confirm, do you mean that should apply even for components that have lengthy fixed styles (meaning they never change dynamically in the component's `Render` method)?

For example, should one always prefer to write:

```Go
style.Width("100%"),
vecty.Style("text-align", "center"),
vecty.Style("background-color", "hsl(209, 51%, 92%)"),
vecty.Style("padding", string(vecty.Px(15))),
vecty.Style("display", "inline-block"),
```

Instead of a single compact line:

```Go
vecty.Property("style", "width: 100%; text-align: center; background-color: hsl(209, 51%, 92%); padding: 15px; display: inline-block;"),
```

Is that so?

I'm okay with that, I just wanted to confirm (before I start rewriting a lot of my code, hehe).

**Comment by slimsag** [comment]
That is correct.

In theory, a static string like `width: 100%; text-align: center; ...` is not strictly worse than individually defined properties except that:

1. It provides more than one way to acomplish the same thing.
2. Strings are very much not type safe, and `vecty.Style(...)` calls could be easily translated into `style.Foobar(...)` calls (probably even automatically with a tool.)
3. Depending on how we decide to handle vendor prefixes long-term (https://github.com/gopherjs/vecty/issues/86) `vecty.Style` or `style.Foobar` may automatically give you vendor prefixes, which would be nicer.
4. It needs special casing to `style.cssText` (as shown here).

**Comment by shurcooL** [comment]
> If anyone wants, please feel free to send a PR for that (or else I will probably over the weekend)

@slimsag, I've made PR #96 that should fix this.
