### ISSUE TITLE
Add CI.

### ISSUE THREAD

**Issue by shurcooL** [gopherjs/vecty#95]
I found it surprising to see this Go project does not have any sort of CI.

I ran into an issue where some of the code wasn't gofmted. I fixed that and wanted to add a gofmt formatting check to `.travis.yml` or equivalent, but couldn't, because there's no CI.

CI should be added so such basic problems don't have to be detected manually.

**Comment by slimsag** [comment]
I absolutely agree; Note that the reason we historically have not had CI yet is because we also don't have tests (!) -- I am working on those, however :)

If anyone wants to beat me to adding a .travis.yml please do!

**Comment by shurcooL** [comment]
> If anyone wants to beat me to adding a .travis.yml please do!

Sure, made #99.
